#pragma once

/**
 * @file phi_spec.h
 * @brief Specification and constants for Gaussian-log (Φ) approximation in TakumCpp.
 * 
 * This header defines the parameters for the LUT + interpolation / hybrid polynomial
 * approximation of the Gaussian-log function Φ used for addition/subtraction in log domain.
 * 
 * Strategy:
 * - For takum16: LUT size 1024, linear interpolation (Q-format Q15.16).
 * - For takum32: LUT size 4096, linear interpolation (Q-format Q15.16).
 * - For takum64+: Coarse LUT size 256, minimax polynomials degree 5-7 per interval (Q-format Q16.16).
 * 
 * Q-format: Fixed-point representation for LUT entries and coefficients. Qm.n means m integer bits, n fractional bits.
 * Error budgets: Per-interval max/mean absolute errors computed offline and included in generated header.
 * 
 * Generated content: #include "generated/phi_coeffs.h" contains poly_coeffs array, max_errors array.
 * To regenerate: Run `python3 scripts/gen_poly_coeffs.py > include/takum/internal/generated/phi_coeffs.h`
 * 
 * Accuracy targets (Proposition 11): Worst-case error per operation within λ(p) ulp bound for the precision.
 * The offline script produces machine-checkable error reports; see gen_poly_coeffs.py for details.
 */

#include <cstdint>

/**
 * @namespace takum::internal::phi
 * @brief Internal implementation of Gaussian-log (Φ) approximation for takum arithmetic.
 *
 * This namespace contains the lookup tables, polynomial coefficients, and constants
 * needed for efficient addition/subtraction in the logarithmic domain. The implementation
 * uses different strategies based on the takum precision:
 * 
 * - takum16: Linear interpolation with 1024-entry LUT
 * - takum32: Linear interpolation with 4096-entry LUT  
 * - takum64+: Hybrid approach with coarse LUT + minimax polynomials
 *
 * @note This is an internal implementation detail and should not be used directly
 * @note Coefficients and error bounds are auto-generated by offline scripts
 */
namespace takum::internal::phi {

/// @brief LUT size for takum16 linear interpolation
constexpr int LUT_SIZE_TAKUM16 = 1024;
/// @brief LUT size for takum32 linear interpolation
constexpr int LUT_SIZE_TAKUM32 = 4096;
/// @brief Coarse LUT size for takum64+ hybrid polynomial approach
constexpr int LUT_SIZE_TAKUM64 = 256;

/// @brief Minimum polynomial degree for minimax approximation
constexpr int POLY_DEGREE_MIN = 5;
/// @brief Maximum polynomial degree for minimax approximation
constexpr int POLY_DEGREE_MAX = 7;
/// @brief Default polynomial degree used for takum64 and larger formats
constexpr int DEFAULT_POLY_DEGREE = 5;

/// @brief Fractional bits in Q-format for takum16 LUT entries (Q15.16)
constexpr int LUT_Q_FRAC_BITS_TAKUM16 = 16;
/// @brief Fractional bits in Q-format for takum32 LUT entries (Q15.16)
constexpr int LUT_Q_FRAC_BITS_TAKUM32 = 16;
/// @brief Fractional bits in Q-format for takum64+ polynomial coefficients (Q16.16)
constexpr int LUT_Q_FRAC_BITS_TAKUM64 = 16;

/// @brief Fractional bits in Q-format for polynomial coefficients
constexpr int POLY_Q_FRAC_BITS = 16;

// Include generated coefficients and error bounds
#include "generated/phi_coeffs.h"

// Interpolation formula: Linear fixed-point (default); cubic details in implementation.
// Worst-case error bounds: Use max_errors[interval] from generated header.
// For Prop 11 guarantee: Sum of Φ errors + rounding in encode/decode < total budget.

}  // namespace takum::internal::phi