name: CI

permissions:
  contents: read

on: [push, pull_request]

jobs:
  # Windows with MSVC - cheapest GitHub Actions runner
  windows-msvc:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Generate polynomial coefficients
        timeout-minutes: 3
        run: |
          python3 scripts/gen_poly_coeffs.py || python scripts/gen_poly_coeffs.py

      - name: Configure with MSVC
        timeout-minutes: 3
        run: cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release

      - name: Build with MSVC
        timeout-minutes: 10
        run: cmake --build build --config Release

      - name: Test with MSVC
        timeout-minutes: 3
        run: cmake --build build --target ci_test_wrapper --config Release
        continue-on-error: true

      - name: Upload MSVC failure log if present
        uses: actions/upload-artifact@v4
        with:
          name: test-failures-msvc-release
          path: build/test_failures.log
          if-no-files-found: ignore

  # Linux with GCC - cheapest GitHub Actions runner
  linux-gcc:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GCC and dependencies
        timeout-minutes: 5
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13 ninja-build python3

      - name: Generate polynomial coefficients
        timeout-minutes: 3
        run: python3 scripts/gen_poly_coeffs.py

      - name: Configure with GCC
        timeout-minutes: 2
        env:
          CC: gcc-13
          CXX: g++-13
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build with GCC
        timeout-minutes: 4
        run: cmake --build build

      - name: Test with GCC
        timeout-minutes: 2
        run: cmake --build build --target ci_test_wrapper
        continue-on-error: true

      - name: Upload failure log if present
        uses: actions/upload-artifact@v4
        with:
          name: test-failures-gcc-release
          path: build/test_failures.log
          if-no-files-found: ignore

  # Linux with Clang - cheapest GitHub Actions runner  
  linux-clang:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Clang and dependencies
        timeout-minutes: 5
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-15 ninja-build python3

      - name: Generate polynomial coefficients
        timeout-minutes: 3
        run: python3 scripts/gen_poly_coeffs.py

      - name: Configure with Clang
        timeout-minutes: 2
        env:
          CC: clang-15
          CXX: clang++-15
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build with Clang
        timeout-minutes: 4
        run: cmake --build build

      - name: Test with Clang
        timeout-minutes: 2
        run: cmake --build build --target ci_test_wrapper
        continue-on-error: true

      - name: Upload failure log if present
        uses: actions/upload-artifact@v4
        with:
          name: test-failures-clang-release
          path: build/test_failures.log
          if-no-files-found: ignore
