name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MSYS2 and Ninja (minimal)
        run: choco install msys2 --no-progress; choco install ninja -y

      - name: Install MinGW-w64 toolchain and update MSYSY
        shell: bash
        run: |
          "C:/msys64/usr/bin/bash.exe" -lc "pacman -Syu --noconfirm"
          "C:/msys64/usr/bin/bash.exe" -lc "pacman -S --needed --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake"

      - name: Add MinGW to PATH
        run: echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check CMake version
        run: cmake --version

      - name: Configure and build (Ninja + GCC, CMake all the way)
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER="C:/msys64/mingw64/bin/gcc.exe" -DCMAKE_CXX_COMPILER="C:/msys64/mingw64/bin/g++.exe"
          cmake --build build --config Debug

      - name: Run tests and capture failures
        run: cmake --build build --target ci_test_wrapper --config Debug
        continue-on-error: true

      - name: Upload failure log if present
        uses: actions/upload-artifact@v4
        with:
          name: test-failures
          path: build/test_failures.log
          if-no-files-found: ignore
